In [1]:
import random
random.seed(2022)

In [5]:
seq1 = random.choices(range(1,20), k=15)
seq2 = random.choices(range(1,20), k=20)

In [6]:
print(seq1)

[1, 15, 6, 18, 17, 7, 8, 2, 8, 9, 1, 5, 10, 2, 3]


In [7]:
print(seq2)

[3, 8, 19, 6, 1, 19, 13, 9, 5, 18, 9, 1, 15, 9, 13, 14, 7, 9, 2, 3]


In [1]:
import numpy as np

In [6]:
mask = np.array([True, False, True, False])

seq = np.array([1 , 2, 3, 4])

seq[~mask] = 0

seq

array([1, 0, 3, 0])

In [10]:
seq1 = np.array([1,1,1,1])

seq2 = seq1.copy()

In [11]:
seq2[2] = 1

print(seq2, seq1)

[1 1 1 1] [1 1 1 1]


In [15]:
np.dot(seq1, 1)

array([1, 1, 1, 1])